[package]
name = "musiman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1.0"

pyo3 = { version = "0.15.1", features = ["auto-initialize", "serde", "anyhow"] }

gstreamer = "0.16"
gstreamer-player = "0.16"